---
apiVersion: v1
kind: ResourceQuota
metadata:
    name: three-resourcequota
    namespace: three-tier
spec:
  hard:
    limits.cpu: "3"
    requests.cpu: "2m"
    limits.memory: "3Gi"
    requests.memory: "2Gi"    
