---
apiVersion: v1
kind: ResourceQuota
metadata:
    name: three-resourcequota
    namespace: three-tier
spec:
  hard:
    limits.cpu: "2000m"
    requests.cpu: "1000m"
    limits.memory: "2Gi"
    requests.memory: "1Gi"    