apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  namespace: three-tier

spec:
  restartPolicy: Never

  containers:
    - name: netshoot
      image: nicolaka/netshoot
      command:
        - sleep
        - "3600"

      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
