---
apiVersion: v1
kind: Secrets
metadata:
    name: mysql-Secrets
    namespace: three-tier
type: Opaque
stringData:
  DB_USERNAME: cm9vdA==
  DB_PASSWORD: ZGV2b3BzcGFzc3dvcmQ=
  RABBITMQ_USERNAME: Z3Vlc3Q=
  RABBITMQ_PASSWORD: Z3Vlc3Q= 